
FROM node:lts-alpine as build-stage
MAINTAINER nobas

WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm i -g @quasar/cli
RUN quasar build

FROM nginx:stable-alpine as production-stage
COPY --from=build-stage /app/dist/spa /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
